openapi: "3.0.0"

info:
  title: Masters of the Universe
  version: "1.0"

paths:
  /characters:
    get:
      summary: Search characters
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 3
                items:
                  $ref: '#/components/schemas/Character'
        # TODO: Add 401 response with errors list

  /characters/{characterId}:
    parameters:
      - $ref: '#/components/parameters/CharacterId'
    get:
      summary: Read a character
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
        # TODO: Add 401 response with errors list
    delete:
      summary: Delete a character
      responses:
        '204':
          description: No Content
        # TODO: Add 401 response with errors list

components:
  parameters:
    CharacterId:
      name: characterId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/CharacterId'
  schemas:
    CharacterId:
      type: string
      pattern: ^[a-z]{3,}$
    Character:
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/CharacterId'
        name:
          type: string
          minLength: 3
          maxLength: 36
        birthDate:
          type: string
          format: date
        age:
          type: integer
          minimum: 0
          maximum: 128
        side:
          type: string
          enum:
            - hero
            - villain
            - neutral
        archEnemyId:
          type: string