openapi: 3.0.0

info:
  title: Masters of the Univers
  version: "1.0"

servers:
  - description: Mock
    url: http://localhost:3100

paths:
  /characters:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 3
                items:
                  $ref: "#/components/schemas/Character"
  /characters/{characterId}:
    get:
      parameters:
        - name: characterId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Character"
components:
  schemas:
    Character:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          minLength: 3
          pattern: ^[0-9][a-z]*$
        name:
          type: string
          minLength: 1
          maxLength: 50
        birthDate:
          type: string
          format: date
        age:
          type: integer
          minimum: 18
          maximum: 256
        side:
          type: string
          enum:
            - hero
            - vilain
        homePlanet:
          type: string