openapi: '3.0.0'

info:
  title: Masters of the Universe
  version: '1.0'

paths:
  /characters:
    get:
      summary: Search characters
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 3
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                      pattern: ^[a-z]{3,}$
                    name:
                      type: string
                      minLength: 3
                      maxLength: 36
                    birthDate:
                      type: string
                      format: date
                    age:
                      type: integer
                      minimum: 0
                      maximum: 128
                    side:
                      type: string
                      enum:
                        - hero
                        - villain
                        - neutral
  # TODO: Add "Read a character" operation